### ISSUE TITLE
Add Dru Modbus TCP protokol pdf

### ISSUE THREAD

**Issue by chbloemer** [snoekieboe/DRU-Modbus-Openhab2-NodeRed#1]
Could you please add the protocol documentation pdf. The link from your thread doesn’t work anymore.

**Comment by snoekieboe** [comment]
I’ve updated the link in my post to point towards my GitHub where the PDF is also available for download.

Br

Roel

**Comment by chbloemer** [comment]
Thanks a lot.

**Comment by chbloemer** [comment]
I am trying to get this working in open hab with Modbus 2.4.0 binding. I have a Dru Metro XTU 100 with Honeywell Bridge (BRDG-03EM01, LinkStatus=Online)

I would like to address Reg. No. 40200 (Action 100 Turn Pilot on)

modbux.things
```
Bridge modbus:tcp:localhostTCP [ host="192.168.x.x", port=502, id=2 ] {

    Thing data holding101 [ readStart="", readValueType="", writeStart="101", writeValueType="int16", writeType="holding" ]
    Thing data holding200 [ readStart="", readValueType="", writeStart="200", writeValueType="int16", writeType="holding" ]

    Bridge poller holding [ start=203, length=1, refresh=1000, type="holding" ] {
        Thing data holding203 [ readStart="203.1", readValueType="bit", writeType="holding" ]
    }

}
```

home.items
```
Number  DruAction	"Actie [%d]"	<setting>     (gKA) {channel="modbus:data:localhostTCP:holding200:number"}
```

home.sitemap
```
Switch item=DruAction mappings=[100="100", 101="101", 2="2", 3="3"]
```
I get for Example this error:

> 2019-01-27 13:31:25.780 [ERROR] [rt.modbus.internal.ModbusManagerImpl] - Last try 3 failed when executing request (ModbusPollerThingHandlerImpl.ModbusPollerReadRequest@1ebd8e2[slaveId=2,functionCode=READ_MULTIPLE_REGISTERS,start=203,length=1,maxTries=3]). Aborting. Error was: net.wimpi.modbus.ModbusSlaveException Error Code = 2 [operation ID 5bbdf772-ecb7-4cf9-b75f-7c1106554d63]

Modbus TCP Slave (modbus:tcp:localhostTCP) is "ONLINE" in the Thing configuration in PaperUI.

Some Questions:
1. Do I need to bind to the gateway somehow? Or can I just send Modbus commands to the gateway. Controling the fire with iPhone App and RF Transmitter works. 
2. Is the "id" always 2?
3. Could you help me with the config to get the first holding to work, to start up the fire? Maybe its just a minor mistake on my side. If I get one thing working the rest should be easy.

**Comment by chbloemer** [comment]
```
    Thing data holding101 "Initiate Binding" [ readStart="", readValueType="", writeStart="40101", writeValueType="uint16", writeType="holding" ]
    Thing data holding200 "Action" [ readStart="", readValueType="", writeStart="40200", writeValueType="uint16", writeType="holding" ]

    Bridge poller holdings "Holdings"[ start=40203, length=1, refresh=5000, type="holding" ] {
        Thing data 203 "Fire Status" [ readStart="40203.1", readValueType="bit" ]
    }
```
I got it working. Just used the wrong numbers. I thought, that the range 40000 is for holding and that I only need for example the value 203.

**Comment by snoekieboe** [comment]
Great! enjoy controlling your DRU fireplace through openhab…. as an example i made a rule that burns the fireplace at 100% for the first 10 minutes ( to get rid of the moisture) and after the 10 minutes in turns to a Eco Wave program. works like a charm..

Br

Roel
